### ISSUE TITLE
TPA Crashes Fabric Snapshot Server

### ISSUE THREAD

**Issue by ItsMCB** [CodedSakura/FabricTPA#10]
While I know this plugin isn't designed to work on Minecraft snapshot 21w08b, it'd be grate if it supported it. Whenever a TPA request is accepted the entire server crashes. I've attached the crash log.
[crash-2021-03-04_21.05.06-server.txt](https://github.com/CodedSakura/FabricTPA/files/6087926/crash-2021-03-04_21.05.06-server.txt)

Minecraft Version: 21w08b
Fabric API: fabric-api-0.31.1+1.17
Plugin Version: FabricTPA-1.4.1

**Comment by CodedSakura** [comment]
Available in tag 1.4.2
