### ISSUE TITLE
LAN issue (probably my fault 🙃)

### ISSUE THREAD

**Issue by spaceclouds42** [CodedSakura/FabricTPA#13]
FabricTPAFixTitles is causing a ClassDefNotFound error, presumably because it has the side set to server, and I was testing on a client LAN server. I was also testing on 21w10a just to see if the snapshot broke it, so I am going to test on LAN server again on 1.16.4 and send an update

[Crash Report](https://paste.gg/p/anonymous/72857e10a26748e987d4839895537e2f)

**Comment by CodedSakura** [comment]
AFAIK FabricTPA won't be loaded in LAN, so idk how you even got an error /shrug

**Comment by spaceclouds42** [comment]
I edited the fabric.mod.json to have side set to * instead of server

**Comment by spaceclouds42** [comment]
Well that was stupid :facepalm: I just tested it on 1.16.5 and of course it didn't cause any errors. *FixTitles is only called if version is ^21w08a.* Should have tested on 21w08a ._.

**Comment by spaceclouds42** [comment]
Tested on 21w08a, still got class not found error, so im 99% sure it's just because the library mod is set to be server sided only, going to quickly fix that
