### ISSUE TITLE
ConfigUtils initialization issue

### ISSUE THREAD

**Issue by EvieTheOwl** [CodedSakura/FabricTPA#17]
**Description:** Crashes when starting the server. Guessing it's failing to read the config maybe
**Crash report:** https://gist.github.com/profjb58/7e0a99fdb059e8e51c8b1e856dbc7792

**Comment by CodedSakura** [comment]
was more of a bug/discrepency with latest FabricWarps & FabricHomes, fixed in their respective v0.2.1 and v0.1.3
