### ISSUE TITLE
This is a mistake when TPA players are playing

### ISSUE THREAD

**Issue by Kaery40** [CodedSakura/FabricTPA#18]
[Timer-82/INFO]: [STDERR]: java.lang.NoSuchFieldError: field_5988
[Timer-82/INFO]: [STDERR]: 	at eu.codedsakura.mods.TeleportUtils$1.run(TeleportUtils.java:65)
[Timer-82/INFO]: [STDERR]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[Timer-82/INFO]: [STDERR]: 	at java.util.TimerThread.run(Timer.java:505)
[Timer-84/INFO]: [STDERR]: java.lang.NoSuchFieldError: field_5988
[Timer-84/INFO]: [STDERR]: 	at eu.codedsakura.mods.TeleportUtils$1.run(TeleportUtils.java:65)
[Timer-84/INFO]: [STDERR]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[Timer-84/INFO]: [STDERR]: 	at java.util.TimerThread.run(Timer.java:505)

**Comment by CodedSakura** [comment]
Can you provide more info on FabricAPI version, FacricTPA version and whether you're using FabricWarps, FabricHomes or other of my mods?

**Comment by Kaery40** [comment]
fabric-api-0.32.9
FabricHomes-0.1.3
FabricTPA-2.0.1
FabricWraps-0.2.1

**Comment by CodedSakura** [comment]
what minecraft version are you using?

**Comment by Kaery40** [comment]
1.17snapshots

**Comment by CodedSakura** [comment]
that explains the mysterious unreproducable bugs, as i don't test on 1.17 snapshots

**Comment by Kaery40** [comment]
Could you test it in the updated mod update?

**Comment by CodedSakura** [comment]
looking at the error itslef it seems mojang have changed something about checking how an entity is removed, so i'd have to make a 1.17 version specifically, for which i don't have time :/

**Comment by Kaery40** [comment]
If you have time, please update it 1.17 please.

**Comment by James76931** [comment]
+1 for a 1.17 version please 😃
If you're not going to make one, I'd recommend removing the message saying this mod is compatible with the 1.17 snapshot on Modrinth and Curseforge. It seems a bit misleading at the moment. 😦

**Comment by CodedSakura** [comment]
as the date of the 1.17 release has been published, i will now start working on a 1.17 version!

**Comment by James76931** [comment]
> as the date of the 1.17 release has been published, i will now start working on a 1.17 version!

Thank you! 🙂

**Comment by CodedSakura** [comment]
done, with 154c0d4a9490897bb450c8aba801ddd49faa6bf5 (v3.0.0)!
