### ISSUE TITLE
Typing /tpacancel with no playername specified should cancel all outgoing requests.

### ISSUE THREAD

**Issue by CalXee** [CodedSakura/FabricTPA#21]
The red error message is from just typing /tpacancel; I expected it to say "Must specify the player you are teleporting to", or just make it cancel every single ongoing teleport requests if you don't specify.

![2021-05-29_17 40 22](https://user-images.githubusercontent.com/68349758/120085314-189cd400-c0a5-11eb-89c5-8a0bc3da29ac.png)

**Comment by CodedSakura** [comment]
I'll probably make it cancel the only active one, as when there's multiple, it should show a choice menu
