### ISSUE TITLE
Config for text values + formatting 

### ISSUE THREAD

**Issue by ghost** [CodedSakura/FabricTPA#23]
hello could you add text editing to the config for possible translations and changing the color of the text?

**Comment by CodedSakura** [comment]
that is already planned in CodedSMPUtils, and i don't think i'll be updating FabricTPA more than bugfixes for now

will leave this issue open though

**Comment by ghost** [comment]
what is codedsmputils .. is it a future mod including tpa, warp, pvp and homes?

**Comment by CodedSakura** [comment]
yep, it is. i'm slowly making progess on it, but i have prostponed it for the last month as uni exams are nearing...

the repo for it is https://github.com/CodedSakura/CodedSMPUtils, and you can follow progess in my Discord server https://discord.gg/BkKG6nx6rG
