### ISSUE TITLE
/back command

### ISSUE THREAD

**Issue by benjamin-andersen** [CodedSakura/FabricTPA#25]
Add a command to teleport to previous location (ideally separate mod compatible with your other teleport mods)

**Comment by CodedSakura** [comment]
sorry for the late reply..
a separate /back command would cause quite a few issues, and so i've been working on a unification of all my mods, [CodedSMPUtils](https://github.com/CodedSakura/CodedSMPUtils) and recently finished the /back module in it

**Comment by benjamin-andersen** [comment]
Yes!!! This is awesome thank you! There aren't many *good* essentials like repos out here for fabric so I appreciate this a LOT :)
