### ISSUE TITLE
Add cooldown gamerule

### ISSUE THREAD

**Issue by nullpanda** [CodedSakura/FabricTPA#4]
Hello,

Please add a cooldown gamerule to specify the minimum time required between teleports.

**Comment by CodedSakura** [comment]
Hi, in your mind, should the cooldown be applied to the user who got teleported, the user who initiated the request, or both users involved? (the former two are different when using /tpahere)

**Comment by nullpanda** [comment]
Only whoever moved.

**Comment by CodedSakura** [comment]
added in v1.4.0!
