### ISSUE TITLE
Requesting teleport, dying, then changing dimensions causes the teleport to not change dimension

### ISSUE THREAD

**Issue by silversquirl** [CodedSakura/FabricTPA#6]
When a player dies, the entity is recreated. However, the entity attached to the TPARequest is not updated to the new entity, meaning its dimension is not updated when the player changes dimension.
However, as the two entities share the same network handler, the `teleport()` call still works and applies the coordinate change to the new player entity, without changing its dimension.

**Comment by CodedSakura** [comment]
Interesting, i currently don't have an idea of how i could fix this issue.  
Also, this is seems super specific :P

**Comment by silversquirl** [comment]
Simplest fix is probably to check the entity's `removed` field before teleporting.

**Comment by CodedSakura** [comment]
So i decided to finally check this out, as @SpaceClouds42 suggested a possible fix.
But, i can't seem to re-create the problem you're having, could you give exact steps for reproducing?
Without being able to recreate it, i can't be sure the issue is fixed...

**Comment by CodedSakura** [comment]
should be fixed in v2.0.0
